version: '3.8'

services:
  app:
    build: .
    image: nodeapp
    ports:
      - "80:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - NODE-ENV=development
    volumes:
      - ".:/app"
    networks:
      pgnodeapp:
    depends_on:
      - db
    command: ["./wait-for", "postgres:5432", "--", "npm", "run", "build-start"]
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      pgnodeapp:
        aliases:
          - "postgres"
    volumes:
      - postgres-db:/var/lib/postgresql/data

networks:
  pgnodeapp:
    driver: bridge

volumes:
  postgres-db: